[Settings]
ID = "8403450c-33e7-47e7-ac2b-18b9efcabc62"

[build]
  command = "npm run build"
  publish="front-end/build"
  base = "front-end"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200